{"uuid": "a42e4007-e8b4-474e-a589-d8b38d2b7ff6", "children": ["2e2a1252-2989-4da8-9c95-94af55511ae8"], "befores": [{"name": "login_setup", "status": "passed", "start": 1715251348173, "stop": 1715251357352}], "afters": [{"name": "login_setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=124.0.6367.118)\nStacktrace:\n#0 0x643e0a07adf3 <unknown>\n#1 0x643e09d694e7 <unknown>\n#2 0x643e09d4ed95 <unknown>\n#3 0x643e09d4f6ef <unknown>\n#4 0x643e09d69a40 <unknown>\n#5 0x643e09d3f6be <unknown>\n#6 0x643e09de5205 <unknown>\n#7 0x643e09dd6418 <unknown>\n#8 0x643e09da728a <unknown>\n#9 0x643e09da7c5e <unknown>\n#10 0x643e0a03f11b <unknown>\n#11 0x643e0a04306b <unknown>\n#12 0x643e0a02b231 <unknown>\n#13 0x643e0a043bd2 <unknown>\n#14 0x643e0a0100ef <unknown>\n#15 0x643e0a069f48 <unknown>\n#16 0x643e0a06a120 <unknown>\n#17 0x643e0a079f44 <unknown>\n#18 0x707a60894ac3 <unknown>\n\n", "trace": "  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 893, in _teardown_yield_fixture\n    next(it)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/testcases/conftest.py\", line 26, in login_setup\n    driver.close()\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in close\n    self.execute(Command.CLOSE)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1715251377748, "stop": 1715251378723}], "start": 1715251348173, "stop": 1715251378723}