{"uuid": "0f11aa01-601e-4d71-97f5-418702439fdb", "children": ["e9ad228a-cadf-4cc5-91e2-bfa31475b261"], "befores": [{"name": "login_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=124.0.6367.118)\nStacktrace:\n#0 0x5c4bedcb5cb3 <unknown>\n#1 0x5c4bed9a44a7 <unknown>\n#2 0x5c4bed99c7a9 <unknown>\n#3 0x5c4bed98c782 <unknown>\n#4 0x5c4bed98dd71 <unknown>\n#5 0x5c4bed98caee <unknown>\n#6 0x5c4bed98c211 <unknown>\n#7 0x5c4bed98c093 <unknown>\n#8 0x5c4bed98a01c <unknown>\n#9 0x5c4bed98a53a <unknown>\n#10 0x5c4bed9a6e2f <unknown>\n#11 0x5c4beda307a5 <unknown>\n#12 0x5c4beda11412 <unknown>\n#13 0x5c4beda2fbe9 <unknown>\n#14 0x5c4beda111b3 <unknown>\n#15 0x5c4bed9e224a <unknown>\n#16 0x5c4bed9e2c1e <unknown>\n#17 0x5c4bedc79fdb <unknown>\n#18 0x5c4bedc7df2b <unknown>\n#19 0x5c4bedc660f1 <unknown>\n#20 0x5c4bedc7ea92 <unknown>\n#21 0x5c4bedc4afaf <unknown>\n#22 0x5c4bedca4e08 <unknown>\n#23 0x5c4bedca4fe0 <unknown>\n#24 0x5c4bedcb4e04 <unknown>\n#25 0x757989094ac3 <unknown>\n\n", "trace": "  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/testcases/conftest.py\", line 16, in login_setup\n    driver.get(baseURL)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1715014104468, "stop": 1715014110861}], "start": 1715014104468, "stop": 1715014111504}