{"uuid": "96da3da3-1b85-4ecd-a6f7-660bbeab98cb", "children": ["3ee19ccf-b742-4897-8f3e-e78e6da7b94e", "1c23bcac-2f53-4db2-9cbd-22937dae0115", "af3ac0d5-e7a3-40b6-abb4-9f152a90cd17", "03f6e175-4a7e-473f-a88d-a691a0bcb88b"], "befores": [{"name": "login_setup1", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000\n  (Session info: chrome=124.0.6367.118)\nStacktrace:\n#0 0x587a0729ddf3 <unknown>\n#1 0x587a06f8c4e7 <unknown>\n#2 0x587a06f743bd <unknown>\n#3 0x587a06f740d3 <unknown>\n#4 0x587a06f7205c <unknown>\n#5 0x587a06f726ef <unknown>\n#6 0x587a06f82c81 <unknown>\n#7 0x587a06f9826e <unknown>\n#8 0x587a06f9d87b <unknown>\n#9 0x587a06f72e32 <unknown>\n#10 0x587a06f97fe5 <unknown>\n#11 0x587a07017af2 <unknown>\n#12 0x587a06ff91f3 <unknown>\n#13 0x587a06fca28a <unknown>\n#14 0x587a06fcac5e <unknown>\n#15 0x587a0726211b <unknown>\n#16 0x587a0726606b <unknown>\n#17 0x587a0724e231 <unknown>\n#18 0x587a07266bd2 <unknown>\n#19 0x587a072330ef <unknown>\n#20 0x587a0728cf48 <unknown>\n#21 0x587a0728d120 <unknown>\n#22 0x587a0729cf44 <unknown>\n#23 0x75ccf2a94ac3 <unknown>\n\n", "trace": "  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/testcases/conftest.py\", line 36, in login_setup1\n    driver.maximize_window()\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 499, in maximize_window\n    self.execute(command, None)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/vishal/PycharmProjects/corporate_Automation_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1715248591625, "stop": 1715248944238}], "start": 1715248591625, "stop": 1715248944900}